name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.11
  - voila==0.5.5
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - ipympl
