name: voila-environment
channels:
  - conda-forge
dependencies:
  - python=3.11.5  # or your preferred Python version
  - voila
  - numpy
  - matplotlib
  - pandas
  - ipympl
  - ipyvolume
  - bqplot
  - scipy
  - xleaflet=0.8.0
  - xeus-cling=0.6.0
